---
title: "Eswatini HBP Testing"
output: html_document
date: "2025-07-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The purpose of this notebook is to test the new features of our Eswatini Health Benefits Package simulations

# Libraries 
```{r}
suppressPackageStartupMessages(library(tidyverse))
library(data.table)
library(magrittr)
library(rsample)
```

## Constants
```{r}
SWZ_CENSUS_YEAR = 2017
SWZ_CENSUS_POP = 1148000 # UN WPP 2019, according to SWZ national census 2017 1093238
```

# Read in data

```{r}
experiment.path = "/gpfs/scratch/citrod01/experiments/eSwatini/HBP/Baseline-campaign_20250715-test___2025_07_16_18_52_46_528668"

test.results <- EMODAnalyzeR::read.simulation.results.bigpurple(
  experiment_path = experiment.path,
  scenario_name =  "test",
  summarize_columns = c("Population","Infected", "On_ART",
                      "Died", "Died_from_HIV",
                      "Newly.Infected","Diagnosed","OnART0","OnART0_preart","OnART1","EffectiveART","NonSuppressiveART"),
  stratify_columns = c("Year", "Age", "Gender", "IP_Key.ARTStatus"),
  min_age_inclusive = 0,
  max_age_inclusive = 99
)

sim.results.pop.scaling <- test.results %>%
  filter(Year == SWZ_CENSUS_YEAR) %>%
  group_by(sim.ix, scenario_name) %>%
  summarize(total.pop = sum(Population), .groups = 'drop_last') %>%
  mutate(pop_scaling_factor = SWZ_CENSUS_POP/total.pop)

test.results <- test.results %>%
  inner_join(
    sim.results.pop.scaling,
    by = c("sim.ix", "scenario_name")
  )
```

# Plots

## Events over time by age

```{r}
test.results %>% 
  filter(Year >= 1990) %>% 
  group_by(Year, Age, Gender, scenario_name, sim.ix) %>% 
  summarize(
    OnART0 = sum(OnART0 * pop_scaling_factor),
    OnART0_preart= sum(OnART0_preart* pop_scaling_factor),
    OnART1= sum(OnART1* pop_scaling_factor),
    EffectiveART= sum(EffectiveART* pop_scaling_factor),
    NonSuppressiveART= sum(NonSuppressiveART* pop_scaling_factor)) %>% 
  group_by(Year, Age, Gender, scenario_name) %>% 
  summarize(
    OnART0 = mean(OnART0),
    OnART0_preart= mean(OnART0_preart),
    OnART1= mean(OnART1),
    EffectiveART= mean(EffectiveART),
    NonSuppressiveART= mean(NonSuppressiveART)) %>% 
  pivot_longer(
    cols = c(OnART0, OnART0_preart, OnART1, EffectiveART, NonSuppressiveART),
    names_to = "metric",
    values_to = "value"
  ) %>% 
  mutate(Age_factor = factor(Age)) %>% 
  ggplot() + 
  geom_point(mapping = aes(x = Year, y = value, color = Age_factor)) + 
  facet_grid(cols = vars(Gender), rows = vars(metric))
```
## ART coverage
```{r}
sim.onart <- test.results %>% 
  dplyr::group_by(Year, Gender, sim.ix) %>% 
  dplyr::summarize(On_ART = sum(On_ART * pop_scaling_factor),
                   Diagnosed = sum(Diagnosed * pop_scaling_factor), 
                   .groups = "keep") %>% 
  ungroup()  %>% 
  mutate(Gender = case_when(Gender==0 ~ "Male", Gender==1 ~ "Female")) %>%
  mutate(ARTcov = case_when(Diagnosed ==0 ~ 0,
                            Diagnosed > 0 ~ On_ART/Diagnosed)) %>%
  group_by(Year, Gender) %>% 
  summarize(On_ART = mean(On_ART),
            Diagnosed = mean(Diagnosed), 
            ARTcov = mean(ARTcov))

sim.onart %>% filter(Year >= 2000, Year <=2025)  %>% 
  ggplot() + 
  geom_line(mapping = aes(x = Year, y =  ARTcov* 100, color = Gender)) + 
  facet_grid(cols = vars(Gender)) +
  scale_color_manual(values=c("blue", "red")) + 
  xlab("Year") +
  ylab("ART Coverage (%)") +
  theme_bw(base_size=16) +
  guides(fill = guide_legend(keywidth = 2, keyheight = 1)) +
  theme(legend.position="bottom") 
```


## Plot ART coverage by age

```{r}
art.coverage.shims <- read.csv(file = "/gpfs/data/bershteynlab/EMOD/citrod01/SWZ_calib/Data/SWZ_ART_SHIMS_2024-07-05.csv")

art.coverage.shims$AgeMin = sapply(strsplit(art.coverage.shims$agecat, "-"), `[`, 1)
art.coverage.shims$AgeMin = as.numeric(art.coverage.shims$AgeMin)
art.coverage.shims$AgeMax = sapply(strsplit(art.coverage.shims$agecat, "-"), `[`, 2)
art.coverage.shims$AgeMax = as.numeric(art.coverage.shims$AgeMax)
art.coverage.shims[is.na(art.coverage.shims$AgeMin),]$AgeMin <- 80
art.coverage.shims[is.na(art.coverage.shims$AgeMax),]$AgeMax <- 100

art.coverage.shims <- art.coverage.shims %>% 
  select(gender, agecat, AgeMin, AgeMax) %>%
  group_by(gender, agecat, AgeMin, AgeMax) %>% 
  slice(1) %>%
  ungroup() %>% 
  mutate(year = 2004, 
         pct_on_art = 0) %>% 
  select(year, gender, agecat, AgeMin, AgeMax, pct_on_art) %>% 
  rbind(art.coverage.shims %>% select(year, gender, agecat, AgeMin, AgeMax, pct_on_art))

art.coverage.shims <- art.coverage.shims %>% select(Year = year, Gender= gender, agecat, AgeMin, AgeMax, pct_on_art)
```

```{r}
art.coverage.shims <- read.csv(file = "/gpfs/data/bershteynlab/EMOD/citrod01/SWZ_calib/Data/SWZ_ART_SHIMS_2024-07-05.csv")

art.coverage.shims$AgeMin = sapply(strsplit(art.coverage.shims$agecat, "-"), `[`, 1)
art.coverage.shims$AgeMin = as.numeric(art.coverage.shims$AgeMin)
art.coverage.shims$AgeMax = sapply(strsplit(art.coverage.shims$agecat, "-"), `[`, 2)
art.coverage.shims$AgeMax = as.numeric(art.coverage.shims$AgeMax)
art.coverage.shims[is.na(art.coverage.shims$AgeMin),]$AgeMin <- 80
art.coverage.shims[is.na(art.coverage.shims$AgeMax),]$AgeMax <- 100

art.coverage.shims <- art.coverage.shims %>% 
  select(gender, agecat, AgeMin, AgeMax) %>%
  group_by(gender, agecat, AgeMin, AgeMax) %>% 
  slice(1) %>%
  ungroup() %>% 
  mutate(year = 2004, 
         pct_on_art = 0) %>% 
  select(year, gender, agecat, AgeMin, AgeMax, pct_on_art) %>% 
  rbind(art.coverage.shims %>% select(year, gender, agecat, AgeMin, AgeMax, pct_on_art))

art.coverage.shims <- art.coverage.shims %>% select(Year = year, Gender= gender, agecat, AgeMin, AgeMax, pct_on_art)
```

Set up plot
```{r}
age_bins = c(15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65)

# Subset data on years
data <- test.results %>% filter(Year >= 2004)

# Age bins
age_labels = c()
for (i in 1:(length(age_bins) - 1)){
  age_labels <- append(age_labels, paste0("[",age_bins[i],":",age_bins[i + 1],")"))
}

# Label each age by its bin
data <- data %>% mutate(
  AgeBin = cut(Age, breaks = age_bins, right = FALSE)
  ) %>%
  filter(!is.na(AgeBin))
data$AgeBin_index = factor(data$AgeBin,labels = 1:8)#length(age_labels))

# Label SHIMS ART coverage data age by bins
art.coverage.shims <- art.coverage.shims %>% 
  mutate(AgeBin = cut(AgeMin, breaks = age_bins, right = FALSE)
         ) %>% 
  filter(!is.na(AgeBin))
art.coverage.shims$AgeBin_index = factor(art.coverage.shims$AgeBin,labels = 1:length(age_labels))

# Calculate prevalence, grouping by age bin
data.prev <- data %>% EMODAnalyzeR::calculate.prevalence(
  stratify_columns = c("Year", "AgeBin_index", "AgeBin", "Gender", "scenario_name", "sim.id"),
  numerator = "On_ART",
  denominator = "Infected")

# Calculate mean ART coverage
data.mean <- data.prev %>%
  dplyr::group_by(Year, AgeBin_index, AgeBin, Gender, scenario_name) %>%
  dplyr::summarize(mean.Prevalence = mean(Prevalence),
            sd.Prevalence = sd(Prevalence),
            .groups = 'keep') %>%
  ungroup() %>%
  dplyr::mutate(upper = mean.Prevalence + 2*sd.Prevalence,
                lower = case_when(mean.Prevalence - 2 * sd.Prevalence > 0 ~ mean.Prevalence - 2 * sd.Prevalence,
                         mean.Prevalence - 2 * sd.Prevalence <= 0 ~ 0)
                )

# Transform data
data.mean <- data.mean %>% mutate(Gender = case_when(Gender==0 ~ "Male", Gender==1 ~ "Female"))
#data.mean
```
```{r, fig.height= 10}
# Plot! 
p <- data.mean %>% filter(Year == floor(Year), Year < 2025, as.numeric(AgeBin_index) < 8) %>% 
  ggplot() +
  # plot means
  geom_point(
    mapping = aes(x = Year, y = mean.Prevalence*100, color = Gender), 
    size=3,
     show.legend = FALSE
  ) +
  geom_line(
    mapping = aes(x = Year, y = mean.Prevalence*100, color = Gender),
    size=2,
     show.legend = FALSE
  ) +
  # plot data
  geom_point(data = art.coverage.shims %>% filter(as.numeric(AgeBin_index) < 8),
             mapping = aes(x = Year, y = pct_on_art), size = 4) + 
  facet_grid(cols = vars(Gender), rows = vars(AgeBin)) +
  xlab("Year") +
  ylab("ART Coverage (%)") +
  theme_bw(base_size=16) +
  guides(fill = guide_legend(keywidth = 2, keyheight = 1)) +
  theme(legend.position="bottom") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(strip.background = element_rect(colour="black", fill="white")) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_color_manual(values=c("blue", "red"))
  
p
```

## VLS Coverage

```{r}
test.results %>% 
  filter(Year >= 2004) %>% 
  dplyr::group_by(Year, Gender, scenario_name, IP_Key.ARTStatus, sim.ix) %>% 
  dplyr::summarize(On_ART = sum(On_ART * pop_scaling_factor), 
                   .groups = "keep") %>% 
  ungroup() %>% 
  mutate(Gender = case_when(Gender==0 ~ "Male", Gender==1 ~ "Female")) %>%
  group_by(Year, Gender, scenario_name, IP_Key.ARTStatus) %>% 
  summarize(On_ART = mean(On_ART), .groups = 'drop_last') %>% 
  pivot_wider(id_cols = c(Year, Gender, scenario_name), 
              names_from = IP_Key.ARTStatus,
              values_from = On_ART) %>% 
  mutate(Total = NeverOnART + OffART + OnARTPreVLS+ OnEffectiveART + OnNonSuppressiveART) %>% 
  mutate(VLS = OnEffectiveART/Total) %>% 
  ggplot() + 
  geom_point(mapping = aes(x = Year, y = VLS)) + 
  facet_wrap(facets = vars(Gender), ncol = 2)
```

## VLS Coverage by Age

```{r, fig.height=10}
test.results %>% 
  filter(Year >= 2004) %>% 
  dplyr::group_by(Year, Age, Gender, scenario_name, IP_Key.ARTStatus, sim.ix) %>% 
  dplyr::summarize(On_ART = sum(On_ART * pop_scaling_factor), 
                   .groups = "keep") %>% 
  ungroup() %>% 
  mutate(Gender = case_when(Gender==0 ~ "Male", Gender==1 ~ "Female")) %>%
  group_by(Year, Age, Gender, scenario_name, IP_Key.ARTStatus) %>% 
  summarize(On_ART = mean(On_ART), .groups = 'drop_last') %>% 
  pivot_wider(id_cols = c(Year, Age, Gender, scenario_name), 
              names_from = IP_Key.ARTStatus,
              values_from = On_ART) %>% 
  mutate(Total = NeverOnART + OffART + OnARTPreVLS+ OnEffectiveART + OnNonSuppressiveART) %>% 
  mutate(VLS = OnEffectiveART/Total) %>% 
  mutate(Age_factor = factor(Age)) %>%
  ggplot() + 
  geom_point(mapping = aes(x = Year, y = VLS)) + 
  scale_y_continuous(limits = c(.75,1)) + 
  facet_grid(cols = vars(Gender), 
             rows = vars(Age_factor)
             )
```

